services:
  - type: web
    name: telegram-video-bot
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7641317425:AAHfWDG6uHQZeG8BQ5JvuvjMFvLFgrqbh9Q
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 3000